interface ExternalResource {
  id: string;
  title: string;
  shortLabel: string;
  description: string;
  href: string;
  citation?: string;
  category: "norma" | "comunicado" | "sistema" | "servico";
  issuingBody?: string;
  appliesTo?: string;
  whyItMatters?: string;
  userWhenToUse?: string;
  lastVerifiedText?: string;
}

export const externalResources = {
  resolution15: {
    id: "resolution15",
    title: "Resolução CD/FNDE nº 15/2021",
    shortLabel: "Resolução nº 15/2021",
    description: "Norma principal do PDDE e base do núcleo mínimo da prestação de contas.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/legislacao/resolucoes/2021/resolucao-no-15-de-16-de-setembro-de-2021/%40%40download/file",
    citation: "Resolução CD/FNDE nº 15/2021",
    category: "norma",
    issuingBody: "FNDE",
    appliesTo: "Núcleo normativo da execução e prestação de contas do PDDE.",
    whyItMatters: "É a principal base federal para conferir o conteúdo mínimo do processo e os deveres da UEx/EEx.",
    userWhenToUse: "Use quando surgir dúvida sobre obrigação documental, execução, fiscalização ou prestação de contas.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  resolution7_2024: {
    id: "resolution7_2024",
    title: "Resolução CD/FNDE nº 7/2024",
    shortLabel: "Resolução nº 7/2024",
    description: "Norma federal relacionada ao BB Gestão Ágil no fluxo do PDDE.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/media-pdde/RESOLUOCD_FNDEN7DE2DEMAIODE2024RESOLUOCD_FNDEN7DE2DEMAIODE2024DOUImprensaNacional.pdf",
    citation: "Resolução CD/FNDE nº 7/2024",
    category: "norma",
    issuingBody: "FNDE",
    appliesTo: "BB Gestão Ágil e registros federais do PDDE, conforme exercício e atualizações.",
    whyItMatters: "Ajuda a separar o processo local no SEI!RIO dos registros em ambiente federal.",
    userWhenToUse: "Consulte quando a dúvida envolver BB Gestão Ágil, sistema federal ou exercício aplicável.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  comunicado47_2024: {
    id: "comunicado47_2024",
    title: "Comunicado PDDE nº 47/2024",
    shortLabel: "Comunicado nº 47/2024",
    description: "Orientação operacional específica para os recursos recebidos em 2024.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/media-pdde/comunicados/2024-1/Comunicadon.47_2024Orientaesparaaprestaodecontasdosrecursosrecebidosem2024.pdf",
    citation: "Comunicado PDDE nº 47/2024",
    category: "comunicado",
    issuingBody: "FNDE",
    appliesTo: "Orientações operacionais para recursos recebidos em 2024.",
    whyItMatters: "Ajuda a interpretar o recorte do exercício e detalhes operacionais relevantes para a conferência.",
    userWhenToUse: "Consulte ao revisar processos do exercício de 2024 e situações específicas daquele ciclo.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  comunicado01_2026: {
    id: "comunicado01_2026",
    title: "Comunicado PDDE nº 01/2026",
    shortLabel: "Comunicado nº 01/2026",
    description: "Esclarecimento oficial do FNDE sobre saldos, estorno e aplicabilidade a partir de 2027.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/media-pdde/comunicados/2026/comunicado-n-01_2026-alteracoes-na-resolucao-cd-fnde-no-7-2024-estorno-de-recurso.pdf",
    citation: "Comunicado PDDE nº 01/2026",
    category: "comunicado",
    issuingBody: "FNDE",
    appliesTo: "Saldos, estorno e efeitos a partir de 2027.",
    whyItMatters: "Evita orientar incorretamente sobre reprogramação, estorno e vigência das mudanças recentes.",
    userWhenToUse: "Consulte quando a dúvida envolver saldo remanescente, estorno ou impacto futuro do exercício.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  bbGestaoAgilFaq: {
    id: "bbGestaoAgilFaq",
    title: "Perguntas e Respostas PDDE (BB Gestão Ágil)",
    shortLabel: "FAQ BB Gestão Ágil",
    description: "Material oficial do FNDE sobre o recorte dos recursos de 2023 e 2024 e a convivência com o SiGPC.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/media-pdde/area-para-gestores/bb-gestao-agil/PerguntaseRespostasPDDE.pdf",
    category: "sistema",
    issuingBody: "FNDE",
    appliesTo: "Uso do BB Gestão Ágil e convivência com outros ambientes federais.",
    whyItMatters: "Ajuda a distinguir execução, registro e análise em sistemas federais diferentes.",
    userWhenToUse: "Consulte quando houver dúvida sobre o que deve estar no BB Gestão Ágil e como isso dialoga com o processo local.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  bbGestaoAgilHub: {
    id: "bbGestaoAgilHub",
    title: "BB Gestão Ágil",
    shortLabel: "BB Gestão Ágil",
    description: "Página oficial do FNDE com manual e orientações da ferramenta.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/media-pdde/area-para-gestores/bb-gestao-agil",
    category: "sistema",
    issuingBody: "FNDE",
    appliesTo: "Página central da solução BB Gestão Ágil.",
    whyItMatters: "Reúne materiais oficiais úteis para entender o ambiente federal aplicável ao exercício.",
    userWhenToUse: "Use quando precisar localizar manual, orientação operacional ou acesso ao hub oficial do sistema.",
    lastVerifiedText: "Verificado em 02 de julho de 2026",
  },
  pddeResolucoes: {
    id: "pddeResolucoes",
    title: "Resoluções e Formulários do PDDE",
    shortLabel: "Resoluções e Formulários",
    description: "Repositório oficial para acompanhar normas e materiais vigentes do programa.",
    href: "https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde/resolucoes-e-formularios",
    category: "norma",
    issuingBody: "FNDE",
    appliesTo: "Repositório oficial de resoluções e formulários do PDDE.",
    whyItMatters: "Funciona como ponto de atualização para mudanças normativas e materiais vigentes do programa.",
    userWhenToUse: "Consulte quando precisar verificar se houve nova resolução, formulário ou material oficial.",
    lastVerifiedText: "Verificado em 28 de março de 2026",
  },
  decreto8539_2015: {
    id: "decreto8539_2015",
    title: "Decreto nº 8.539/2015",
    shortLabel: "Decreto nº 8.539/2015",
    description: "Marco federal sobre processos eletrônicos e distinção entre documento nato-digital e digitalizado.",
    href: "https://www.planalto.gov.br/ccivil_03/_Ato2015-2018/2015/Decreto/D8539.htm",
    citation: "Decreto nº 8.539/2015",
    category: "norma",
    issuingBody: "Presidência da República",
    appliesTo: "Processo eletrônico e distinção entre documento nato-digital e digitalizado.",
    whyItMatters: "Sustenta a diferença entre autenticação, original nato-digital e documento digitalizado.",
    userWhenToUse: "Use quando a dúvida envolver validade documental ou natureza do arquivo inserido no SEI!RIO.",
    lastVerifiedText: "Verificado em 28 de março de 2026",
  },
  decretoProcessoRio_47769_2020: {
    id: "decretoProcessoRio_47769_2020",
    title: "Decreto Rio nº 47.769/2020",
    shortLabel: "Decreto Rio nº 47.769/2020",
    description: "Norma municipal do processo eletrônico com definições de documento nato-digital e digitalizado.",
    href: "https://doweb.rio.rj.gov.br/apifront/portal/edicoes/publicacoes_ver_conteudo/671238",
    citation: "Decreto Rio nº 47.769/2020",
    category: "norma",
    issuingBody: "Município do Rio de Janeiro",
    appliesTo: "Processo eletrônico municipal, classificação documental e fluxo local de documentos digitais.",
    whyItMatters: "Ajuda a sustentar localmente a distinção entre documento digitalizado, nato-digital e documento produzido no sistema.",
    userWhenToUse: "Consulte quando a dúvida envolver a base municipal do processo eletrônico e do tratamento documental no rito local.",
    lastVerifiedText: "Verificado em 12 de abril de 2026",
  },
  seiRioPortal: {
    id: "seiRioPortal",
    title: "SEI!RIO",
    shortLabel: "SEI!RIO",
    description: "Acesso ao sistema oficial.",
    href: "https://sei.rio/",
    category: "servico",
    issuingBody: "Prefeitura do Rio de Janeiro",
    appliesTo: "Acesso direto ao ambiente oficial do SEI!RIO.",
    whyItMatters: "É a porta de entrada operacional do fluxo local.",
    userWhenToUse: "Use para acessar o sistema ou orientar usuários que precisam entrar no ambiente oficial.",
    lastVerifiedText: "Verificado em 28 de março de 2026",
  },
  seiRioUserGuide: {
    id: "seiRioUserGuide",
    title: "Guia do Usuário Interno",
    shortLabel: "Guia do Usuário Interno",
    description: "Manual oficial do SEI!RIO para uso interno.",
    href: "https://sei.rio/servidor/guias-e-ambiente-de-teste/guia-do-usuario-interno/",
    category: "servico",
    issuingBody: "Prefeitura do Rio de Janeiro",
    appliesTo: "Manual institucional do usuário interno do SEI!RIO.",
    whyItMatters: "Complementa o guia quando a dúvida é sobre uso do sistema e não sobre mérito do PDDE.",
    userWhenToUse: "Consulte para dúvidas operacionais gerais do SEI!RIO fora do recorte específico deste guia.",
    lastVerifiedText: "Verificado em 28 de março de 2026",
  },
  seiRioSupport: {
    id: "seiRioSupport",
    title: "Portal de Atendimento",
    shortLabel: "Portal de Atendimento",
    description: "Canal oficial de suporte técnico do SEI!RIO.",
    href: "https://sei.rio/servidor/atendimento/",
    category: "servico",
    issuingBody: "Prefeitura do Rio de Janeiro",
    appliesTo: "Suporte técnico oficial do SEI!RIO.",
    whyItMatters: "Ajuda a encaminhar corretamente problemas técnicos que não se resolvem com orientação editorial.",
    userWhenToUse: "Use quando houver falha de acesso, erro de sistema ou necessidade de atendimento técnico.",
    lastVerifiedText: "Verificado em 28 de março de 2026",
  },
} as const satisfies Record<string, ExternalResource>;

export type ExternalResourceId = keyof typeof externalResources;

export const officialReferenceIds: ExternalResourceId[] = [
  "resolution15",
  "resolution7_2024",
  "comunicado47_2024",
  "bbGestaoAgilFaq",
  "comunicado01_2026",
  "bbGestaoAgilHub",
  "pddeResolucoes",
];

export const referenceGovernanceIds: ExternalResourceId[] = [
  "resolution15",
  "resolution7_2024",
  "comunicado47_2024",
  "comunicado01_2026",
  "bbGestaoAgilFaq",
  "bbGestaoAgilHub",
  "pddeResolucoes",
  "decreto8539_2015",
  "decretoProcessoRio_47769_2020",
  "seiRioUserGuide",
  "seiRioSupport",
];

export const externalResourceList = Object.values(externalResources);
