import { createRoot } from "react-dom/client";
import "@fontsource/plus-jakarta-sans/latin-600.css";
import "@fontsource/plus-jakarta-sans/latin-700.css";
import "@fontsource/plus-jakarta-sans/latin-800.css";
import "@fontsource/public-sans/latin-400.css";
import "@fontsource/public-sans/latin-500.css";
import "@fontsource/public-sans/latin-600.css";
import "@fontsource/public-sans/latin-700.css";
import "@fontsource/source-serif-4/latin-400.css";
import "@fontsource/source-serif-4/latin-600.css";
import "@fontsource/source-serif-4/latin-700.css";
import App from "./App.tsx";
import "./index.css";
import "./styles/institutional-polish.css";
import "./styles/light-contrast.css";
import "./styles/wcag-warning.css";
import "./styles/editorial-contemporary.css";
import "./styles/editorial-semantic.css";
import "./styles/editorial-accessibility.css";
import "./styles/editorial-reference-system.css";
import "./styles/editorial-reference-components.css";

createRoot(document.getElementById("root")!).render(<App />);
